export interface Quantization {
  name: string;
  bits: number;
  vramGB: number;
  diskGB: number;
  quality: string;
}

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  family: string;
  params: string;
  paramsBillions: number;
  activeParams?: string;
  architecture: "dense" | "moe";
  releaseDate: string | null;
  contextLength: number;
  useCase: string[];
  description: string;
  url: string;
  minRamGB: number;
  recommendedRamGB: number;
  quants: Quantization[];
  moe?: { numExperts: number; activeExperts: number; activeParameters: number };
  hfDownloads?: number;
  hfLikes?: number;
  ollamaId?: string;
  lmStudioId?: string;
  featured?: boolean;
  tools?: boolean;
  thinking?: boolean;
  license?: string;
}

// ── Helper to compute quants from param count ─────────────

// ~0.5 GB constant overhead for KV cache + inference runtime (llama.cpp, CUDA/Metal context)
const RUNTIME_OVERHEAD_GB = 0.5;

function makeQuants(paramsB: number): Quantization[] {
  const totalParams = paramsB * 1_000_000_000;
  const vram = (bpp: number) => Math.round(Math.max((totalParams * bpp) / (1024 ** 3) * 1.1 + RUNTIME_OVERHEAD_GB, 0.5) * 10) / 10;
  const disk = (bpp: number) => Math.round(Math.max((totalParams * bpp) / (1024 ** 3) * 1.05, 0.1) * 10) / 10;

  return [
    { name: "Q2_K", bits: 2, vramGB: vram(0.3125), diskGB: disk(0.3125), quality: "low" },
    { name: "Q3_K_M", bits: 3, vramGB: vram(0.4375), diskGB: disk(0.4375), quality: "moderate" },
    { name: "Q4_K_M", bits: 4, vramGB: vram(0.5), diskGB: disk(0.5), quality: "good" },
    { name: "Q5_K_M", bits: 5, vramGB: vram(0.625), diskGB: disk(0.625), quality: "good" },
    { name: "Q6_K", bits: 6, vramGB: vram(0.75), diskGB: disk(0.75), quality: "excellent" },
    { name: "Q8_0", bits: 8, vramGB: vram(1.0), diskGB: disk(1.0), quality: "excellent" },
    { name: "F16", bits: 16, vramGB: vram(2.0), diskGB: disk(2.0), quality: "lossless" },
  ];
}

function ram(paramsB: number): { min: number; rec: number } {
  const totalParams = paramsB * 1_000_000_000;
  const modelSizeGB = (totalParams * 0.5) / (1024 ** 3);
  return {
    min: Math.round(Math.max(modelSizeGB * 1.2, 1.0) * 10) / 10,
    rec: Math.round(Math.max(modelSizeGB * 2.0, 2.0) * 10) / 10,
  };
}

// ── Real GGUF file sizes from HuggingFace ─────────────────
// Run `pnpm exec tsx scripts/fetch-gguf-sizes.ts` to regenerate.
import ggufSizesData from "./gguf-sizes.json";
const ggufSizes: Record<string, Record<string, number>> = ggufSizesData;

function applyRealSizes(modelId: string, quants: Quantization[]): Quantization[] {
  const sizes = ggufSizes[modelId];
  if (!sizes) return quants;
  return quants
    .filter((q) => q.name in sizes)
    .map((q) => ({ ...q, diskGB: sizes[q.name] ?? q.diskGB }));
}

// ── Try to load scraped data ──────────────────────────────
let scrapedModels: AIModel[] | null = null;

// ── Static fallback model list ────────────────────────────

const STATIC_MODELS: AIModel[] = [
  // Tiny (<2B)
  { id: "qwen3.5-0.8b", name: "Qwen 3.5 0.8B", provider: "Alibaba", family: "Qwen", params: "0.8B", paramsBillions: 0.8, architecture: "dense", releaseDate: "2026-02", contextLength: 32768, useCase: ["chat", "edge"], description: "Ultra-tiny model for embedded and edge", url: "https://huggingface.co/lmstudio-community/Qwen3.5-0.8B-GGUF", minRamGB: ram(0.8).min, recommendedRamGB: ram(0.8).rec, quants: makeQuants(0.8), ollamaId: "qwen3.5:0.8b", thinking: true, license: "Apache 2.0" },
  { id: "qwen3-0.6b", name: "Qwen 3 0.6B", provider: "Alibaba", family: "Qwen", params: "0.6B", paramsBillions: 0.6, architecture: "dense", releaseDate: "2025-04", contextLength: 32768, useCase: ["chat", "edge"], description: "Ultra-light Qwen 3 model for constrained devices", url: "https://huggingface.co/lmstudio-community/Qwen3-0.6B-GGUF", minRamGB: ram(0.6).min, recommendedRamGB: ram(0.6).rec, quants: makeQuants(0.6), thinking: true, license: "Apache 2.0" },
  { id: "llama3.2-1b", name: "Llama 3.2 1B", provider: "Meta", family: "Llama", params: "1B", paramsBillions: 1, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "edge"], description: "Meta's smallest Llama for edge devices", url: "https://huggingface.co/meta-llama/Llama-3.2-1B", minRamGB: ram(1).min, recommendedRamGB: ram(1).rec, quants: makeQuants(1), ollamaId: "llama3.2:1b", tools: true, license: "Llama 3.2 Community" },
  { id: "gemma3-1b", name: "Gemma 3 1B", provider: "Google", family: "Gemma", params: "1B", paramsBillions: 1, architecture: "dense", releaseDate: "2025-03", contextLength: 32768, useCase: ["chat", "edge"], description: "Google's tiny Gemma for on-device", url: "https://huggingface.co/google/gemma-3-1b-it", minRamGB: ram(1).min, recommendedRamGB: ram(1).rec, quants: makeQuants(1), ollamaId: "gemma3:1b", lmStudioId: "gemma-3", license: "Gemma" },
  { id: "tinyllama-1.1b", name: "TinyLlama 1.1B", provider: "Community", family: "Llama", params: "1.1B", paramsBillions: 1.1, architecture: "dense", releaseDate: "2024-01", contextLength: 2048, useCase: ["chat", "edge"], description: "Ultralight model for constrained devices", url: "https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0", minRamGB: ram(1.1).min, recommendedRamGB: ram(1.1).rec, quants: makeQuants(1.1), ollamaId: "tinyllama", license: "Apache 2.0" },
  { id: "qwen2.5-coder-1.5b", name: "Qwen 2.5 Coder 1.5B", provider: "Alibaba", family: "Qwen", params: "1.5B", paramsBillions: 1.5, architecture: "dense", releaseDate: "2024-11", contextLength: 32768, useCase: ["code"], description: "Ultra-lightweight coding model", url: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct", minRamGB: ram(1.5).min, recommendedRamGB: ram(1.5).rec, quants: makeQuants(1.5), ollamaId: "qwen2.5-coder:1.5b", license: "Apache 2.0" },
  { id: "deepseek-r1-1.5b", name: "DeepSeek R1 1.5B", provider: "DeepSeek", family: "DeepSeek", params: "1.5B", paramsBillions: 1.5, architecture: "dense", releaseDate: "2025-01", contextLength: 65536, useCase: ["reasoning"], description: "Tiny reasoning model distilled from R1", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B", minRamGB: ram(1.5).min, recommendedRamGB: ram(1.5).rec, quants: makeQuants(1.5), ollamaId: "deepseek-r1:1.5b", lmStudioId: "deepseek-r1", thinking: true, license: "MIT" },
  { id: "qwen3-1.7b", name: "Qwen 3 1.7B", provider: "Alibaba", family: "Qwen", params: "1.7B", paramsBillions: 1.7, architecture: "dense", releaseDate: "2025-04", contextLength: 32768, useCase: ["chat", "multilingual"], description: "Compact multilingual Qwen 3", url: "https://huggingface.co/Qwen/Qwen3-1.7B", minRamGB: ram(1.7).min, recommendedRamGB: ram(1.7).rec, quants: makeQuants(1.7), ollamaId: "qwen3:1.7b", lmStudioId: "qwen3-2504", thinking: true, license: "Apache 2.0" },
  { id: "qwen3.5-2b", name: "Qwen 3.5 2B", provider: "Alibaba", family: "Qwen", params: "2B", paramsBillions: 2, architecture: "dense", releaseDate: "2026-02", contextLength: 32768, useCase: ["chat", "multilingual"], description: "Small multimodal Qwen 3.5", url: "https://huggingface.co/lmstudio-community/Qwen3.5-2B-GGUF", minRamGB: ram(2).min, recommendedRamGB: ram(2).rec, quants: makeQuants(2), ollamaId: "qwen3.5:2b", thinking: true, license: "Apache 2.0" },
  // Small (2-5B)
  { id: "gemma2-2b", name: "Gemma 2 2B", provider: "Google", family: "Gemma", params: "2B", paramsBillions: 2, architecture: "dense", releaseDate: "2024-06", contextLength: 8192, useCase: ["chat", "edge"], description: "Google's compact open model", url: "https://huggingface.co/google/gemma-2-2b-it", minRamGB: ram(2).min, recommendedRamGB: ram(2).rec, quants: makeQuants(2), ollamaId: "gemma2:2b", license: "Gemma" },
  { id: "llama3.2-3b", name: "Llama 3.2 3B", provider: "Meta", family: "Llama", params: "3B", paramsBillions: 3, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "code"], description: "Lightweight Llama for mobile and edge", url: "https://huggingface.co/meta-llama/Llama-3.2-3B", minRamGB: ram(3).min, recommendedRamGB: ram(3).rec, quants: makeQuants(3), ollamaId: "llama3.2:3b", tools: true, license: "Llama 3.2 Community" },
  { id: "smollm3-3b", name: "SmolLM3 3B", provider: "HuggingFace", family: "SmolLM", params: "3B", paramsBillions: 3, architecture: "dense", releaseDate: "2025-07", contextLength: 131072, useCase: ["chat", "reasoning"], description: "Lightweight multilingual reasoning", url: "https://huggingface.co/HuggingFaceTB/SmolLM3-3B", minRamGB: ram(3).min, recommendedRamGB: ram(3).rec, quants: makeQuants(3), license: "Apache 2.0" },
  { id: "phi-3.5-mini", name: "Phi-3.5 Mini", provider: "Microsoft", family: "Phi", params: "3.8B", paramsBillions: 3.8, architecture: "dense", releaseDate: "2024-08", contextLength: 131072, useCase: ["reasoning", "code", "chat"], description: "Microsoft's efficient small model with long context", url: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct", minRamGB: ram(3.8).min, recommendedRamGB: ram(3.8).rec, quants: makeQuants(3.8), ollamaId: "phi3.5", license: "MIT" },
  { id: "phi-4-mini-reasoning", name: "Phi-4 Mini Reasoning", provider: "Microsoft", family: "Phi", params: "3.8B", paramsBillions: 3.8, architecture: "dense", releaseDate: "2025-04", contextLength: 16384, useCase: ["reasoning"], description: "Lightweight reasoning model", url: "https://huggingface.co/microsoft/Phi-4-mini-reasoning", minRamGB: ram(3.8).min, recommendedRamGB: ram(3.8).rec, quants: makeQuants(3.8), ollamaId: "phi4-mini-reasoning", lmStudioId: "phi-4-reasoning", thinking: true, license: "MIT" },
  { id: "qwen3-4b", name: "Qwen 3 4B", provider: "Alibaba", family: "Qwen", params: "4B", paramsBillions: 4, architecture: "dense", releaseDate: "2025-04", contextLength: 32768, useCase: ["chat", "code"], description: "Compact Qwen 3 for general tasks", url: "https://huggingface.co/Qwen/Qwen3-4B", minRamGB: ram(4).min, recommendedRamGB: ram(4).rec, quants: makeQuants(4), ollamaId: "qwen3:4b", lmStudioId: "qwen3-2504", tools: true, thinking: true, license: "Apache 2.0" },
  { id: "gemma3-4b", name: "Gemma 3 4B", provider: "Google", family: "Gemma", params: "4B", paramsBillions: 4, architecture: "dense", releaseDate: "2025-03", contextLength: 131072, useCase: ["chat", "vision"], description: "Multimodal Gemma with 128K context", url: "https://huggingface.co/google/gemma-3-4b-it", minRamGB: ram(4).min, recommendedRamGB: ram(4).rec, quants: makeQuants(4), ollamaId: "gemma3:4b", lmStudioId: "gemma-3", license: "Gemma" },
  { id: "qwen3.5-4b", name: "Qwen 3.5 4B", provider: "Alibaba", family: "Qwen", params: "4B", paramsBillions: 4, architecture: "dense", releaseDate: "2026-02", contextLength: 32768, useCase: ["chat", "multilingual"], description: "Small multimodal Qwen 3.5", url: "https://huggingface.co/lmstudio-community/Qwen3.5-4B-GGUF", minRamGB: ram(4).min, recommendedRamGB: ram(4).rec, quants: makeQuants(4), ollamaId: "qwen3.5:4b", thinking: true, license: "Apache 2.0" },
  { id: "gemma4-e2b-it", name: "Gemma 4 E2B IT", provider: "Google", family: "Gemma", params: "5B", paramsBillions: 5, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["chat", "vision"], description: "Gemma 4 efficient instruct model (official)", url: "https://huggingface.co/lmstudio-community/gemma-4-E2B-it-GGUF", minRamGB: ram(5).min, recommendedRamGB: ram(5).rec, quants: makeQuants(5), license: "Gemma" },
  { id: "gemma4-e2b", name: "Gemma 4 E2B", provider: "Google", family: "Gemma", params: "5B", paramsBillions: 5, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["vision"], description: "Gemma 4 efficient base model (official)", url: "https://huggingface.co/google/gemma-4-E2B", minRamGB: ram(5).min, recommendedRamGB: ram(5).rec, quants: makeQuants(5), license: "Gemma" },
  { id: "gemma4-e4b-it", name: "Gemma 4 E4B IT", provider: "Google", family: "Gemma", params: "8B", paramsBillions: 8, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["chat", "vision"], description: "Gemma 4 balanced instruct model (official)", url: "https://huggingface.co/lmstudio-community/gemma-4-E4B-it-GGUF", minRamGB: ram(8).min, recommendedRamGB: ram(8).rec, quants: makeQuants(8), license: "Gemma" },
  { id: "gemma4-e4b", name: "Gemma 4 E4B", provider: "Google", family: "Gemma", params: "8B", paramsBillions: 8, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["vision"], description: "Gemma 4 balanced base model (official)", url: "https://huggingface.co/google/gemma-4-E4B", minRamGB: ram(8).min, recommendedRamGB: ram(8).rec, quants: makeQuants(8), license: "Gemma" },
  // Medium (5-10B)
  { id: "mistral-7b", name: "Mistral 7B v0.3", provider: "Mistral AI", family: "Mistral", params: "7B", paramsBillions: 7, architecture: "dense", releaseDate: "2024-05", contextLength: 32768, useCase: ["chat", "reasoning"], description: "High-quality 7B with sliding window attention", url: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3", minRamGB: ram(7).min, recommendedRamGB: ram(7).rec, quants: makeQuants(7), ollamaId: "mistral", lmStudioId: "mistral", tools: true, license: "Apache 2.0" },
  { id: "qwen2.5-7b", name: "Qwen 2.5 7B", provider: "Alibaba", family: "Qwen", params: "7B", paramsBillions: 7, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "multilingual", "code"], description: "Strong multilingual and coding capabilities", url: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct", minRamGB: ram(7).min, recommendedRamGB: ram(7).rec, quants: makeQuants(7), ollamaId: "qwen2.5:7b", tools: true, license: "Apache 2.0" },
  { id: "qwen2.5-coder-7b", name: "Qwen 2.5 Coder 7B", provider: "Alibaba", family: "Qwen", params: "7B", paramsBillions: 7, architecture: "dense", releaseDate: "2024-11", contextLength: 131072, useCase: ["code"], description: "Dedicated coding model", url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct", minRamGB: ram(7).min, recommendedRamGB: ram(7).rec, quants: makeQuants(7), ollamaId: "qwen2.5-coder:7b", tools: true, license: "Apache 2.0" },
  { id: "deepseek-r1-7b", name: "DeepSeek R1 Distill 7B", provider: "DeepSeek", family: "DeepSeek", params: "7B", paramsBillions: 7, architecture: "dense", releaseDate: "2025-01", contextLength: 65536, useCase: ["reasoning"], description: "R1 reasoning distilled into Qwen 7B", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", minRamGB: ram(7).min, recommendedRamGB: ram(7).rec, quants: makeQuants(7), ollamaId: "deepseek-r1:7b", lmStudioId: "deepseek-r1", thinking: true, license: "MIT" },
  { id: "llama3.1-8b", name: "Llama 3.1 8B", provider: "Meta", family: "Llama", params: "8B", paramsBillions: 8, architecture: "dense", releaseDate: "2024-07", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Meta's versatile 8B — great quality/speed ratio", url: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct", minRamGB: ram(8).min, recommendedRamGB: ram(8).rec, quants: makeQuants(8), ollamaId: "llama3.1:8b", featured: true, tools: true, license: "Llama 3.1 Community" },
  { id: "qwen3-8b", name: "Qwen 3 8B", provider: "Alibaba", family: "Qwen", params: "8B", paramsBillions: 8, architecture: "dense", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Qwen 3 with thinking mode support", url: "https://huggingface.co/Qwen/Qwen3-8B", minRamGB: ram(8).min, recommendedRamGB: ram(8).rec, quants: makeQuants(8), ollamaId: "qwen3:8b", lmStudioId: "qwen3-2504", tools: true, thinking: true, license: "Apache 2.0" },
  { id: "ministral-8b", name: "Ministral 8B", provider: "Mistral AI", family: "Mistral", params: "8B", paramsBillions: 8, architecture: "dense", releaseDate: "2024-10", contextLength: 32768, useCase: ["chat"], description: "Mistral's efficient 8B model", url: "https://huggingface.co/mistralai/Ministral-8B-Instruct-2410", minRamGB: ram(8).min, recommendedRamGB: ram(8).rec, quants: makeQuants(8), ollamaId: "ministral-3:8b", lmStudioId: "ministral", tools: true, license: "MRL" },
  { id: "gemma2-9b", name: "Gemma 2 9B", provider: "Google", family: "Gemma", params: "9B", paramsBillions: 9, architecture: "dense", releaseDate: "2024-06", contextLength: 8192, useCase: ["chat", "reasoning"], description: "Google's best mid-size open model", url: "https://huggingface.co/google/gemma-2-9b-it", minRamGB: ram(9).min, recommendedRamGB: ram(9).rec, quants: makeQuants(9), ollamaId: "gemma2:9b", license: "Gemma" },
  { id: "glm-4-9b", name: "GLM-4 9B", provider: "Zhipu AI", family: "GLM", params: "9B", paramsBillions: 9, architecture: "dense", releaseDate: "2024-06", contextLength: 131072, useCase: ["chat", "multilingual", "code"], description: "Multilingual model supporting 26 languages with 128K context", url: "https://huggingface.co/THUDM/glm-4-9b-chat", minRamGB: ram(9).min, recommendedRamGB: ram(9).rec, quants: makeQuants(9), ollamaId: "glm4:9b", tools: true, license: "GLM-4" },
  { id: "nemotron-nano-9b", name: "Nemotron Nano 9B v2", provider: "NVIDIA", family: "Nemotron", params: "9B", paramsBillions: 9, architecture: "dense", releaseDate: "2025-06", contextLength: 131072, useCase: ["reasoning"], description: "Hybrid Mamba2 architecture for reasoning", url: "https://huggingface.co/nvidia/NVIDIA-Nemotron-Nano-9B-v2", minRamGB: ram(9).min, recommendedRamGB: ram(9).rec, quants: makeQuants(9), thinking: true, license: "NVIDIA Open" },
  { id: "qwen3.5-9b", name: "Qwen 3.5 9B", provider: "Alibaba", family: "Qwen", params: "9B", paramsBillions: 9, architecture: "dense", releaseDate: "2026-02", contextLength: 32768, useCase: ["chat", "vision"], description: "Multimodal Qwen 3.5 mid-size", url: "https://huggingface.co/lmstudio-community/Qwen3.5-9B-GGUF", minRamGB: ram(9).min, recommendedRamGB: ram(9).rec, quants: makeQuants(9), ollamaId: "qwen3.5:9b", featured: true, thinking: true, license: "Apache 2.0" },
  // Large (10-30B)
  { id: "llama3.2-11b-vision", name: "Llama 3.2 11B Vision", provider: "Meta", family: "Llama", params: "11B", paramsBillions: 11, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "vision"], description: "Multimodal vision and text model", url: "https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct", minRamGB: ram(11).min, recommendedRamGB: ram(11).rec, quants: makeQuants(11), ollamaId: "llama3.2-vision:11b", tools: true, license: "Llama 3.2 Community" },
  { id: "gemma3-12b", name: "Gemma 3 12B", provider: "Google", family: "Gemma", params: "12B", paramsBillions: 12, architecture: "dense", releaseDate: "2025-03", contextLength: 131072, useCase: ["chat", "vision", "reasoning"], description: "Multimodal Gemma with 128K context", url: "https://huggingface.co/google/gemma-3-12b-it", minRamGB: ram(12).min, recommendedRamGB: ram(12).rec, quants: makeQuants(12), ollamaId: "gemma3:12b", lmStudioId: "gemma-3", license: "Gemma" },
  { id: "mistral-nemo-12b", name: "Mistral Nemo 12B", provider: "Mistral AI", family: "Mistral", params: "12B", paramsBillions: 12, architecture: "dense", releaseDate: "2024-07", contextLength: 131072, useCase: ["chat", "multilingual"], description: "Multilingual 12B with 128K context", url: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407", minRamGB: ram(12).min, recommendedRamGB: ram(12).rec, quants: makeQuants(12), ollamaId: "mistral-nemo", lmStudioId: "mistral-nemo", tools: true, license: "Apache 2.0" },
  { id: "qwen2.5-14b", name: "Qwen 2.5 14B", provider: "Alibaba", family: "Qwen", params: "14B", paramsBillions: 14, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "multilingual", "reasoning"], description: "Excellent quality for its size class", url: "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct", minRamGB: ram(14).min, recommendedRamGB: ram(14).rec, quants: makeQuants(14), ollamaId: "qwen2.5:14b", tools: true, license: "Apache 2.0" },
  { id: "phi-4-14b", name: "Phi-4 14B", provider: "Microsoft", family: "Phi", params: "14B", paramsBillions: 14, architecture: "dense", releaseDate: "2024-12", contextLength: 16384, useCase: ["reasoning", "code"], description: "Microsoft's reasoning-focused model", url: "https://huggingface.co/microsoft/phi-4", minRamGB: ram(14).min, recommendedRamGB: ram(14).rec, quants: makeQuants(14), ollamaId: "phi4", lmStudioId: "phi-4", featured: true, tools: true, license: "MIT" },
  { id: "qwen3-14b", name: "Qwen 3 14B", provider: "Alibaba", family: "Qwen", params: "14B", paramsBillions: 14, architecture: "dense", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Strong all-rounder with thinking mode", url: "https://huggingface.co/Qwen/Qwen3-14B", minRamGB: ram(14).min, recommendedRamGB: ram(14).rec, quants: makeQuants(14), ollamaId: "qwen3:14b", lmStudioId: "qwen3-2504", tools: true, thinking: true, license: "Apache 2.0" },
  { id: "deepseek-r1-14b", name: "DeepSeek R1 Distill 14B", provider: "DeepSeek", family: "DeepSeek", params: "14B", paramsBillions: 14, architecture: "dense", releaseDate: "2025-01", contextLength: 65536, useCase: ["reasoning"], description: "R1 reasoning distilled into Qwen 14B", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", minRamGB: ram(14).min, recommendedRamGB: ram(14).rec, quants: makeQuants(14), ollamaId: "deepseek-r1:14b", lmStudioId: "deepseek-r1", thinking: true, license: "MIT" },
  { id: "llama4-scout-17b", name: "Llama 4 Scout 17B", provider: "Meta", family: "Llama", params: "109B", paramsBillions: 109, activeParams: "17B active", architecture: "moe", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "vision", "reasoning"], description: "MoE with 16 experts, 17B active params", url: "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct", minRamGB: ram(109).min, recommendedRamGB: ram(109).rec, quants: makeQuants(109), moe: { numExperts: 16, activeExperts: 1, activeParameters: 17_000_000_000 }, ollamaId: "llama4:scout", tools: true, featured: true, license: "Llama 4 Community" },
  { id: "gpt-oss-20b", name: "GPT-OSS 20B", provider: "OpenAI", family: "GPT-OSS", params: "21B", paramsBillions: 21, activeParams: "3.6B active", architecture: "moe", releaseDate: "2025-08", contextLength: 131072, useCase: ["chat", "reasoning", "code"], description: "OpenAI's open-weight MoE with configurable reasoning", url: "https://huggingface.co/openai/gpt-oss-20b", minRamGB: ram(21).min, recommendedRamGB: ram(21).rec, quants: makeQuants(21), moe: { numExperts: 16, activeExperts: 2, activeParameters: 3_600_000_000 }, tools: true, ollamaId: "gpt-oss:20b", lmStudioId: "gpt-oss", featured: true, license: "Apache 2.0" },
  { id: "lfm2-24b", name: "LFM2 24B", provider: "Liquid AI", family: "LFM", params: "24B", paramsBillions: 24, activeParams: "2.3B active", architecture: "moe", releaseDate: "2025-11", contextLength: 32768, useCase: ["chat", "edge", "rag"], description: "Hybrid MoE with convolution+attention layers — 2.3B active", url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B", minRamGB: ram(24).min, recommendedRamGB: ram(24).rec, quants: makeQuants(24), moe: { numExperts: 64, activeExperts: 4, activeParameters: 2_300_000_000 }, ollamaId: "lfm2:24b", lmStudioId: "lfm2-24b-a2b", license: "Liquid AI" },
  { id: "devstral-small-2-24b", name: "Devstral Small 2 24B", provider: "Mistral AI", family: "Mistral", params: "24B", paramsBillions: 24, architecture: "dense", releaseDate: "2025-12", contextLength: 262144, useCase: ["code"], description: "Coding-focused model with 256K context — 68% SWE-bench", url: "https://huggingface.co/mistralai/Devstral-Small-2-24B-Instruct-2512", minRamGB: ram(24).min, recommendedRamGB: ram(24).rec, quants: makeQuants(24), ollamaId: "devstral-small-2", lmStudioId: "devstral", license: "Apache 2.0" },
  { id: "mistral-small-24b", name: "Mistral Small 3.1 24B", provider: "Mistral AI", family: "Mistral", params: "24B", paramsBillions: 24, architecture: "dense", releaseDate: "2025-03", contextLength: 131072, useCase: ["chat", "vision", "code"], description: "Multimodal Mistral with vision support", url: "https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503", minRamGB: ram(24).min, recommendedRamGB: ram(24).rec, quants: makeQuants(24), ollamaId: "mistral-small", lmStudioId: "mistral-small", featured: true, tools: true, license: "Apache 2.0" },
  { id: "gemma2-27b", name: "Gemma 2 27B", provider: "Google", family: "Gemma", params: "27B", paramsBillions: 27, architecture: "dense", releaseDate: "2024-06", contextLength: 8192, useCase: ["chat", "reasoning"], description: "Google's largest Gemma 2 model", url: "https://huggingface.co/google/gemma-2-27b-it", minRamGB: ram(27).min, recommendedRamGB: ram(27).rec, quants: makeQuants(27), ollamaId: "gemma2:27b", license: "Gemma" },
  { id: "gemma3-27b", name: "Gemma 3 27B", provider: "Google", family: "Gemma", params: "27B", paramsBillions: 27, architecture: "dense", releaseDate: "2025-03", contextLength: 131072, useCase: ["chat", "vision", "reasoning"], description: "Google's flagship Gemma 3 model", url: "https://huggingface.co/google/gemma-3-27b-it", minRamGB: ram(27).min, recommendedRamGB: ram(27).rec, quants: makeQuants(27), ollamaId: "gemma3:27b", lmStudioId: "gemma-3", featured: true, tools: true, license: "Gemma" },
  { id: "gemma4-26b-a4b-it", name: "Gemma 4 26B-A4B IT", provider: "Google", family: "Gemma", params: "27B", paramsBillions: 27, activeParams: "4B active", architecture: "moe", releaseDate: "2026-04", contextLength: 262144, useCase: ["chat", "vision", "reasoning"], description: "Gemma 4 MoE instruct model (official)", url: "https://huggingface.co/lmstudio-community/gemma-4-26B-A4B-it-GGUF", minRamGB: ram(27).min, recommendedRamGB: ram(27).rec, quants: makeQuants(27), moe: { numExperts: 26, activeExperts: 4, activeParameters: 4_000_000_000 }, license: "Gemma" },
  { id: "gemma4-26b-a4b", name: "Gemma 4 26B-A4B", provider: "Google", family: "Gemma", params: "27B", paramsBillions: 27, activeParams: "4B active", architecture: "moe", releaseDate: "2026-04", contextLength: 262144, useCase: ["vision", "reasoning"], description: "Gemma 4 MoE base model (official)", url: "https://huggingface.co/google/gemma-4-26B-A4B", minRamGB: ram(27).min, recommendedRamGB: ram(27).rec, quants: makeQuants(27), moe: { numExperts: 26, activeExperts: 4, activeParameters: 4_000_000_000 }, license: "Gemma" },
  { id: "qwen3.5-27b", name: "Qwen 3.5 27B", provider: "Alibaba", family: "Qwen", params: "27.8B", paramsBillions: 27.8, architecture: "dense", releaseDate: "2026-02", contextLength: 262144, useCase: ["chat", "vision", "reasoning"], description: "Flagship native multimodal Qwen 3.5", url: "https://huggingface.co/lmstudio-community/Qwen3.5-27B-GGUF", minRamGB: ram(27.8).min, recommendedRamGB: ram(27.8).rec, quants: makeQuants(27.8), ollamaId: "qwen3.5:27b", thinking: true, license: "Apache 2.0" },
  // XL (30-80B)
  { id: "gemma4-31b-it", name: "Gemma 4 31B IT", provider: "Google", family: "Gemma", params: "33B", paramsBillions: 33, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["chat", "vision", "reasoning"], description: "Gemma 4 flagship instruct model (official)", url: "https://huggingface.co/lmstudio-community/gemma-4-31B-it-GGUF", minRamGB: ram(33).min, recommendedRamGB: ram(33).rec, quants: makeQuants(33), license: "Gemma" },
  { id: "gemma4-31b", name: "Gemma 4 31B", provider: "Google", family: "Gemma", params: "33B", paramsBillions: 33, architecture: "dense", releaseDate: "2026-04", contextLength: 262144, useCase: ["vision", "reasoning"], description: "Gemma 4 flagship base model (official)", url: "https://huggingface.co/google/gemma-4-31B", minRamGB: ram(33).min, recommendedRamGB: ram(33).rec, quants: makeQuants(33), license: "Gemma" },
  { id: "qwen3-30b-a3b", name: "Qwen 3 30B-A3B", provider: "Alibaba", family: "Qwen", params: "30B", paramsBillions: 30, activeParams: "3.3B active", architecture: "moe", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "reasoning"], description: "MoE with only 3.3B active — extremely efficient", url: "https://huggingface.co/Qwen/Qwen3-30B-A3B", minRamGB: ram(30).min, recommendedRamGB: ram(30).rec, quants: makeQuants(30), moe: { numExperts: 128, activeExperts: 8, activeParameters: 3_300_000_000 }, tools: true, thinking: true, ollamaId: "qwen3:30b-a3b", lmStudioId: "qwen3-2504", license: "Apache 2.0" },
  { id: "nemotron-nano-30b", name: "Nemotron 3 Nano 30B", provider: "NVIDIA", family: "Nemotron", params: "30B", paramsBillions: 30, activeParams: "3B active", architecture: "moe", releaseDate: "2025-06", contextLength: 1048576, useCase: ["chat", "reasoning"], description: "MoE with 1M context and 3B active", url: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16", minRamGB: ram(30).min, recommendedRamGB: ram(30).rec, quants: makeQuants(30), moe: { numExperts: 128, activeExperts: 6, activeParameters: 3_000_000_000 }, ollamaId: "nemotron-3-nano:30b", lmStudioId: "nemotron-3", thinking: true, license: "NVIDIA Open" },
  { id: "qwen2.5-32b", name: "Qwen 2.5 32B", provider: "Alibaba", family: "Qwen", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "multilingual", "reasoning"], description: "High-quality reasoning and multilingual", url: "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), ollamaId: "qwen2.5:32b", tools: true, license: "Apache 2.0" },
  { id: "qwen2.5-coder-32b", name: "Qwen 2.5 Coder 32B", provider: "Alibaba", family: "Qwen", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2024-11", contextLength: 131072, useCase: ["code"], description: "Best open-source coding model at release", url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), ollamaId: "qwen2.5-coder:32b", featured: true, tools: true, license: "Apache 2.0" },
  { id: "qwen3-32b", name: "Qwen 3 32B", provider: "Alibaba", family: "Qwen", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Qwen 3 flagship dense model", url: "https://huggingface.co/Qwen/Qwen3-32B", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), ollamaId: "qwen3:32b", lmStudioId: "qwen3-2504", featured: true, tools: true, thinking: true, license: "Apache 2.0" },
  { id: "deepseek-r1-32b", name: "DeepSeek R1 Distill 32B", provider: "DeepSeek", family: "DeepSeek", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2025-01", contextLength: 65536, useCase: ["reasoning"], description: "R1 reasoning distilled into Qwen 32B — sweet spot", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), ollamaId: "deepseek-r1:32b", lmStudioId: "deepseek-r1", featured: true, thinking: true, license: "MIT" },
  { id: "exaone-4-32b", name: "EXAONE 4.0 32B", provider: "LG AI", family: "EXAONE", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2025-07", contextLength: 131072, useCase: ["chat", "reasoning"], description: "Hybrid reasoning, multilingual", url: "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), license: "EXAONE AI" },
  { id: "olmo2-32b", name: "OLMo 2 32B", provider: "Allen AI", family: "OLMo", params: "32B", paramsBillions: 32, architecture: "dense", releaseDate: "2025-03", contextLength: 4096, useCase: ["chat", "reasoning"], description: "Fully open research model by Allen AI", url: "https://huggingface.co/allenai/OLMo-2-0325-32B-Instruct", minRamGB: ram(32).min, recommendedRamGB: ram(32).rec, quants: makeQuants(32), license: "Apache 2.0" },
  { id: "command-r-35b", name: "Command R 35B", provider: "Cohere", family: "Command", params: "35B", paramsBillions: 35, architecture: "dense", releaseDate: "2024-03", contextLength: 131072, useCase: ["chat", "rag"], description: "Optimized for retrieval-augmented generation", url: "https://huggingface.co/CohereForAI/c4ai-command-r-v01", minRamGB: ram(35).min, recommendedRamGB: ram(35).rec, quants: makeQuants(35), ollamaId: "command-r:35b", tools: true, license: "CC BY-NC 4.0" },
  { id: "qwen3.5-35b-a3b", name: "Qwen 3.5 35B-A3B", provider: "Alibaba", family: "Qwen", params: "35B", paramsBillions: 35, activeParams: "3B active", architecture: "moe", releaseDate: "2026-02", contextLength: 262144, useCase: ["chat", "vision"], description: "Efficient multimodal MoE with 3B active", url: "https://huggingface.co/lmstudio-community/Qwen3.5-35B-A3B-GGUF", minRamGB: ram(35).min, recommendedRamGB: ram(35).rec, quants: makeQuants(35), moe: { numExperts: 256, activeExperts: 8, activeParameters: 3_000_000_000 }, ollamaId: "qwen3.5:35b-a3b", thinking: true, license: "Apache 2.0" },
  { id: "mixtral-8x7b", name: "Mixtral 8x7B", provider: "Mistral AI", family: "Mistral", params: "47B", paramsBillions: 47, activeParams: "12.9B active", architecture: "moe", releaseDate: "2023-12", contextLength: 32768, useCase: ["chat", "code"], description: "MoE with 12.9B active params", url: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1", minRamGB: ram(47).min, recommendedRamGB: ram(47).rec, quants: makeQuants(47), moe: { numExperts: 8, activeExperts: 2, activeParameters: 12_900_000_000 }, tools: true, ollamaId: "mixtral:8x7b", license: "Apache 2.0" },
  // XXL (70B+)
  { id: "llama3.3-70b", name: "Llama 3.3 70B", provider: "Meta", family: "Llama", params: "70B", paramsBillions: 70, architecture: "dense", releaseDate: "2024-12", contextLength: 131072, useCase: ["chat", "reasoning", "code"], description: "Best open model at 70B class", url: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct", minRamGB: ram(70).min, recommendedRamGB: ram(70).rec, quants: makeQuants(70), ollamaId: "llama3.3:70b", featured: true, tools: true, license: "Llama 3.3 Community" },
  { id: "gpt-oss-120b", name: "GPT-OSS 120B", provider: "OpenAI", family: "GPT-OSS", params: "117B", paramsBillions: 117, activeParams: "5.1B active", architecture: "moe", releaseDate: "2025-08", contextLength: 131072, useCase: ["chat", "reasoning", "code"], description: "OpenAI's flagship open-weight MoE — 52.6% SWE-bench", url: "https://huggingface.co/openai/gpt-oss-120b", minRamGB: ram(117).min, recommendedRamGB: ram(117).rec, quants: makeQuants(117), moe: { numExperts: 16, activeExperts: 2, activeParameters: 5_100_000_000 }, tools: true, ollamaId: "gpt-oss:120b", lmStudioId: "gpt-oss", featured: true, license: "Apache 2.0" },
  { id: "devstral-2-123b", name: "Devstral 2 123B", provider: "Mistral AI", family: "Mistral", params: "123B", paramsBillions: 123, architecture: "dense", releaseDate: "2025-12", contextLength: 262144, useCase: ["code"], description: "Dense 123B coding model — 72.2% SWE-bench Verified", url: "https://huggingface.co/mistralai/Devstral-2-123B-Instruct-2512", minRamGB: ram(123).min, recommendedRamGB: ram(123).rec, quants: makeQuants(123), ollamaId: "devstral-2", lmStudioId: "devstral-2", featured: true, license: "MRL" },
  { id: "qwen2.5-72b", name: "Qwen 2.5 72B", provider: "Alibaba", family: "Qwen", params: "72B", paramsBillions: 72, architecture: "dense", releaseDate: "2024-09", contextLength: 131072, useCase: ["chat", "multilingual", "reasoning", "code"], description: "Alibaba's flagship open model", url: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct", minRamGB: ram(72).min, recommendedRamGB: ram(72).rec, quants: makeQuants(72), ollamaId: "qwen2.5:72b", tools: true, license: "Qwen" },
  { id: "qwen3.5-122b-a10b", name: "Qwen 3.5 122B-A10B", provider: "Alibaba", family: "Qwen", params: "122B", paramsBillions: 122, activeParams: "10B active", architecture: "moe", releaseDate: "2026-02", contextLength: 262144, useCase: ["chat", "vision", "reasoning"], description: "Large multimodal MoE", url: "https://huggingface.co/lmstudio-community/Qwen3.5-122B-A10B-GGUF", minRamGB: ram(122).min, recommendedRamGB: ram(122).rec, quants: makeQuants(122), moe: { numExperts: 256, activeExperts: 8, activeParameters: 10_000_000_000 }, ollamaId: "qwen3.5:122b-a10b", thinking: true, license: "Apache 2.0" },
  { id: "mixtral-8x22b", name: "Mixtral 8x22B", provider: "Mistral AI", family: "Mistral", params: "141B", paramsBillions: 141, activeParams: "39B active", architecture: "moe", releaseDate: "2024-04", contextLength: 65536, useCase: ["chat", "code", "reasoning"], description: "Large MoE with 39B active params", url: "https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1", minRamGB: ram(141).min, recommendedRamGB: ram(141).rec, quants: makeQuants(141), moe: { numExperts: 8, activeExperts: 2, activeParameters: 39_100_000_000 }, ollamaId: "mixtral:8x22b", tools: true, license: "Apache 2.0" },
  { id: "llama4-maverick-17b-128e", name: "Llama 4 Maverick 17B-128E", provider: "Meta", family: "Llama", params: "400B", paramsBillions: 400, activeParams: "17B active", architecture: "moe", releaseDate: "2025-04", contextLength: 1048576, useCase: ["chat", "vision", "reasoning", "code"], description: "Multimodal MoE with 128 experts — 17B active, 1M context", url: "https://huggingface.co/meta-llama/Llama-4-Maverick-17B-128E-Instruct", minRamGB: ram(400).min, recommendedRamGB: ram(400).rec, quants: makeQuants(400), moe: { numExperts: 128, activeExperts: 1, activeParameters: 17_000_000_000 }, tools: true, ollamaId: "llama4:maverick", license: "Llama 4 Community" },
  { id: "qwen3-235b-a22b", name: "Qwen 3 235B-A22B", provider: "Alibaba", family: "Qwen", params: "235B", paramsBillions: 235, activeParams: "22B active", architecture: "moe", releaseDate: "2025-04", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Massive MoE with 22B active — frontier quality", url: "https://huggingface.co/Qwen/Qwen3-235B-A22B", minRamGB: ram(235).min, recommendedRamGB: ram(235).rec, quants: makeQuants(235), moe: { numExperts: 128, activeExperts: 8, activeParameters: 22_000_000_000 }, ollamaId: "qwen3:235b-a22b", lmStudioId: "qwen3-2504", tools: true, thinking: true, license: "Apache 2.0" },
  { id: "qwen3.5-397b-a17b", name: "Qwen 3.5 397B-A17B", provider: "Alibaba", family: "Qwen", params: "397B", paramsBillions: 397, activeParams: "17B active", architecture: "moe", releaseDate: "2026-02", contextLength: 262144, useCase: ["chat", "vision", "reasoning", "code"], description: "Largest multimodal Qwen 3.5 MoE", url: "https://huggingface.co/Qwen/Qwen3.5-397B-A17B", minRamGB: ram(397).min, recommendedRamGB: ram(397).rec, quants: makeQuants(397), moe: { numExperts: 256, activeExperts: 8, activeParameters: 17_000_000_000 }, ollamaId: "qwen3.5:397b-cloud", thinking: true, license: "Apache 2.0" },
  { id: "llama3.1-405b", name: "Llama 3.1 405B", provider: "Meta", family: "Llama", params: "405B", paramsBillions: 405, architecture: "dense", releaseDate: "2024-07", contextLength: 131072, useCase: ["chat", "reasoning", "code"], description: "Largest open-weight dense model by Meta", url: "https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct", minRamGB: ram(405).min, recommendedRamGB: ram(405).rec, quants: makeQuants(405), ollamaId: "llama3.1:405b", tools: true, license: "Llama 3.1 Community" },
  { id: "qwen3-coder-480b", name: "Qwen 3 Coder 480B", provider: "Alibaba", family: "Qwen", params: "480B", paramsBillions: 480, activeParams: "35B active", architecture: "moe", releaseDate: "2025-07", contextLength: 262144, useCase: ["code"], description: "Largest open coding MoE — 35B active", url: "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct", minRamGB: ram(480).min, recommendedRamGB: ram(480).rec, quants: makeQuants(480), moe: { numExperts: 128, activeExperts: 8, activeParameters: 35_000_000_000 }, ollamaId: "qwen3-coder:480b", lmStudioId: "qwen3-coder", thinking: true, license: "Apache 2.0" },
  { id: "deepseek-r1", name: "DeepSeek R1", provider: "DeepSeek", family: "DeepSeek", params: "671B", paramsBillions: 671, activeParams: "37B active", architecture: "moe", releaseDate: "2025-01", contextLength: 65536, useCase: ["reasoning"], description: "Massive MoE reasoning model — 37B active", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1", minRamGB: ram(671).min, recommendedRamGB: ram(671).rec, quants: makeQuants(671), moe: { numExperts: 256, activeExperts: 8, activeParameters: 37_000_000_000 }, thinking: true, ollamaId: "deepseek-r1:671b", lmStudioId: "deepseek-r1", featured: true, license: "MIT" },
  { id: "deepseek-v3.1", name: "DeepSeek V3.1", provider: "DeepSeek", family: "DeepSeek", params: "671B", paramsBillions: 671, activeParams: "37B active", architecture: "moe", releaseDate: "2025-08", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "Improved V3 with hybrid thinking and tool use", url: "https://huggingface.co/deepseek-ai/DeepSeek-V3-0324", minRamGB: ram(671).min, recommendedRamGB: ram(671).rec, quants: makeQuants(671), moe: { numExperts: 256, activeExperts: 8, activeParameters: 37_000_000_000 }, ollamaId: "deepseek-v3.1", tools: true, license: "MIT" },
  { id: "deepseek-v3.2", name: "DeepSeek V3.2", provider: "DeepSeek", family: "DeepSeek", params: "685B", paramsBillions: 685, activeParams: "37B active", architecture: "moe", releaseDate: "2025-12", contextLength: 131072, useCase: ["chat", "code", "reasoning"], description: "State-of-the-art MoE — 37B active params", url: "https://huggingface.co/deepseek-ai/DeepSeek-V3.2", featured: true, minRamGB: ram(685).min, recommendedRamGB: ram(685).rec, quants: makeQuants(685), moe: { numExperts: 256, activeExperts: 8, activeParameters: 37_000_000_000 }, ollamaId: "deepseek-v3.2", tools: true, license: "MIT" },
  { id: "kimi-k2", name: "Kimi K2", provider: "Moonshot AI", family: "Kimi", params: "1T", paramsBillions: 1000, activeParams: "32B active", architecture: "moe", releaseDate: "2025-07", contextLength: 131072, useCase: ["chat", "reasoning", "code"], description: "1T-param MoE with 384 experts — 32B active, strong agentic coding", url: "https://huggingface.co/moonshotai/Kimi-K2-Instruct", minRamGB: ram(1000).min, recommendedRamGB: ram(1000).rec, quants: makeQuants(1000), moe: { numExperts: 384, activeExperts: 8, activeParameters: 32_000_000_000 }, tools: true, ollamaId: "kimi-k2", featured: true, license: "Kimi" },
];

// ── License helpers ────────────────────────────────────────

const COMMERCIAL_LICENSES = new Set([
  "Apache 2.0", "MIT", "CC BY 4.0", "Gemma", "NVIDIA Open",
  "Llama 3.1 Community", "Llama 3.2 Community", "Llama 3.3 Community", "Llama 4 Community",
]);

export function isCommercialLicense(license?: string): boolean {
  if (!license) return false;
  return COMMERCIAL_LICENSES.has(license);
}

export type LicenseTier = "open" | "partial" | "restricted";

const OPEN_LICENSES = new Set(["Apache 2.0", "MIT", "CC BY 4.0"]);
const PARTIAL_LICENSES = new Set([
  "Gemma", "NVIDIA Open",
  "Llama 3.1 Community", "Llama 3.2 Community", "Llama 3.3 Community", "Llama 4 Community",
]);

export function getLicenseTier(license?: string): LicenseTier {
  if (!license) return "restricted";
  if (OPEN_LICENSES.has(license)) return "open";
  if (PARTIAL_LICENSES.has(license)) return "partial";
  return "restricted";
}

export const LICENSE_LIST = [...new Set(
  STATIC_MODELS.map(m => m.license).filter(Boolean) as string[]
)].sort();

// ── Export ─────────────────────────────────────────────────

const withRealSizes = (scrapedModels || STATIC_MODELS).map((m) => {
  const patched = applyRealSizes(m.id, m.quants);
  return patched.length > 0 ? { ...m, quants: patched } : m;
});

export const models: AIModel[] = withRealSizes;
